# Generated by Django 6.0.2 on 2026-02-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_rental_extended_months_rental_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(),
        ),
    ]
